Repository the-via/keyboards, pull requests merged in 2022-07, with the labels that each got.

#1016 Added Rooboard65
  src/skippys_custom_pcs/rooboard65/rooboard65.json
Labels: pending QMK merge

#1165 Add Kyuu Hotswap PCB to VIA
  src/fjlabs/kyuu/kyuu.json
Labels: pending QMK merge

#1033 Add nullbits TIDBIT
  src/nullbitsco/tidbit.json
Labels: pending QMK merge

#1053 Add mini winni
  src/mini_winni/mini_winni.json
Labels: pending QMK merge

#1125 add baguette66 keyboard
  src/kbdfans/baguette66/baguette66rgb.json
  src/kbdfans/baguette66/baguette66soldered.json
Labels: pending QMK merge

#1127 Adds Amber80_solder & VCL65_solder
  src/sawnsprojects/amber80_solder/amber80_solder.json
  src/sawnsprojects/vcl65_solder/vcl65_solder.json
Labels: pending QMK merge

#1137 Add sandbox keyboard
  src/dailycraft/sandbox/sandbox_rev1.json
  src/dailycraft/sandbox/sandbox_rev2.json
Labels: pending QMK merge

#1173 Add damapad
  src/damapad/damapad.json
Labels: pending QMK merge

#1168 feat: add JJ50 KPRepublic keyboard
  src/kprepublic/jj50.json
  v3/kprepublic/jj50.json
Labels: pending QMK merge

#128 Add support for Hasu's Alps64
  src/hasu/alps64.json
Labels: bug

#1193 json design file for ryanbaekr rb69
  src/ryanbaekr/rb18.json
  src/ryanbaekr/rb69.json
Labels: blocked

#1209 Add support for Typ65+
  src/kopibeng/typ65/typ65.json
Labels: blocked

#1290 Updated for SKergo updates in qmk/qmk_firmware#17384
  src/skergo/skergo.json
Labels: question

#1308 Add json for Work Louder Micro macropad
  src/work_louder/micro.json
Labels: pending QMK merge

#1333 feat: add ymdk split 64 keyboard
  v3/YMDK/sp64/sp64.json
Labels: blocked
