Repository the-via/keyboards, pull requests merged in 2022-12, with the labels that each got.

#1483 Add VIA Support for the GoPolar GG86
  src/gopolar/gg86/gg86.json
Labels: pending QMK merge

#1508 add kbdpad_mk3 support
  src/kbdfans/kbdpad_mk3/kbdpad_mk3.json
Labels: pending QMK merge

#1552 Add VIA support for Zed60
  v3/mechlovin/zed60/zed60.json
Labels: bug

#1573 add tofu_ii keyboard support
  src/dztech/tofu_ii/tofu_ii.json
  v3/dztech/tofu_ii/tofu_ii.json
Labels: blocked

#1563 Update layouts of Dimple Plus
  src/lazydesigners/dimpleplus.json
  v3/lazydesigners/dimpleplus.json
Labels: blocked

#1567 Add the GHS.XLS
  src/ghs/xls.json
  v3/ghs/xls.json
Labels: blocked

#1568 add mw80.json
  src/mwstudio/mw80.json
  v3/mwstudio/mw80.json
Labels: blocked

#1572 add tofu_jr keyboard
  src/dztech/tofu_jr/tofu_jr.json
  v3/dztech/tofu_jr/tofu_jr.json
Labels: blocked

#1574 add support for navi60
  src/navi60/navi60.json
  v3/navi60/navi60.json
Labels: blocked
