Repository the-via/keyboards, pull requests merged in 2024-10, with the labels that each got.

#2346 Fix spelling mistake on custom RGB effects
  src/yiancardesigns/nebula12b/nebula12b.json
  src/yiancardesigns/nebula68b/nebula68b.json
  src/yiancardesigns/nk20/nk20.json
  src/yiancardesigns/nk65b/nk65b.json
  v3/coban/pad9a/pad9a.json
  v3/doio/kb12/kb12-01.json
  v3/doio/kb30/kb30-01.json
  v3/dotmod/dymium65.json
  v3/dp3000/dp3000-rev1.json
  v3/era/sirind/tomak/tomak.json
  v3/geekboards/macropad_v2/macropad_v2.json
  v3/mechlovin/adelais/adelais_en_ciel-rev3.json
  v3/momokai/momokai_tap_duo.json
  v3/momokai/momokai_tap_trio.json
  v3/qwertykeys/qk100/qk100_ansi.json
  v3/wilba_tech/wt6_kh/wt6_kh.json
  v3/wilba_tech/wt8_kh/wt8_kh.json
  v3/xelus/pachi/xelus_pachi_rgb_rev2.json
Labels: bug

#2308 Add boardsource/the_q
  v3/boardsource/the_q/the_q.json
Labels: needs work

#2350 Update support for s6xty
  v3/trnthsn/s6xty/s6xty.json
  v3/trnthsn/tyson60s/tyson60s.json
Labels: pending VIA keymap merge
