Repository the-via/keyboards, pull requests merged in 2025-04, with the labels that each got.

#2404 Adding 1u center column layout to Promenade (HS)
  v3/kradoindustries/promenade/promenade.json
Labels: needs work

#2412 Add Keychron C2 Pro V2 JSONs
  v3/keychron/c2_pro_v2/c2_pro_v2_ansi_rgb.json
  v3/keychron/c2_pro_v2/c2_pro_v2_ansi_white.json
Labels: pending QMK merge, pending VIA keymap merge

#2405 Update skiller_sgk50_s4 keyboard
  v3/sharkoon/skiller_sgk50_s4/skiller_sgk50_s4.json
Labels: develop merged, pending VIA keymap merge

#2411 Add Keychron C1 Pro V2 JSONs
  v3/keychron/c1_pro_v2/c1_pro_v2_ansi_non_light.json
  v3/keychron/c1_pro_v2/c1_pro_v2_ansi_rgb.json
  v3/keychron/c1_pro_v2/c1_pro_v2_ansi_white.json
Labels: pending QMK merge, pending VIA keymap merge

#2427 add uzu42
  v3/uzu42/uzu42.json
Labels: invalid, needs work
